name: Design Tokens

on:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
      figma:
        type: string
        required: false
        default: r3DaPti2Qo22xQXCs77r6T

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  update-tokens:
    name: Update Tokens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JS
        uses: ./.github/composite/setup-js

      - name: Setup Committer Bot Identity
        run: |
          git config --global user.name 'Frontend Platform Bot'
          git config --global user.email 'no-reply@kueski.com'

      - name: Generate PR branch name
        id: branch
        run: |
          BRANCH=$PROVIDED_BRANCH

          if [ -z "$BRANCH" ]; then
            DATE=$(date '+%Y-%m-%d')
            BRANCH="token-update-$DATE"
          fi

          echo "pr_branch=$BRANCH" >> "$GITHUB_OUTPUT"
        env:
          PROVIDED_BRANCH: ${{ inputs.branch }}

      - name: Create and checkout to branch
        run: |
          branch_exist=$(git ls-remote --heads origin refs/heads/$BRANCH)

          if [ -z "$branch_exist" ]; then
            echo "Branch $BRANCH wasn't found, creating..."
            git checkout -b $BRANCH
          else
            echo "Branch $BRANCH already exist, checking out..."
            git fetch origin $BRANCH
            git checkout $BRANCH
            git pull
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.branch.outputs.pr_branch }}

      - name: Download tokens
        run: |
          pnpm cli download-tokens \
            --figmaDocumentId=$FIGMA_FILE \
            --output=cli/parseTokensCommand/rawTokens.ts
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE: ${{ inputs.figma || 'r3DaPti2Qo22xQXCs77r6T' }}

      - name: Parse Tokens
        run: |
          pnpm cli parse-tokens

      - name: Commit and push
        run: |
          git add lib cli
          git commit -m "feat($BRANCH): Update Design Tokens"
          git push -u origin $BRANCH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.branch.outputs.pr_branch }}

      - name: Create PR
        run: |
          DATE=$(date '+%Y-%m-%d')
          gh pr create \
            -t "feat($BRANCH): Update Design Tokens - $DATE" \
            -b "Syncing design tokens with Figma latest updates"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.branch.outputs.pr_branch }}
